<?php
$lang = [
    'en' => [
        'welcome' => 'Welcome to ScreenMix',
        'upload_files' => 'Upload Files',
        'my_files' => 'My Files',
        'profile' => 'Profile',
        'logout' => 'Logout',
        'register' => 'Register',
        'login' => 'Login',
        'username' => 'Username',
        'email' => 'Email',
        'password' => 'Password',
        'submit' => 'Submit',
        'already_have_account' => 'Already have an account?',
        'dont_have_account' => 'Don\'t have an account?',
        'file_name' => 'File Name',
        'uploaded_at' => 'Uploaded At',
        'download' => 'Download',
        'delete' => 'Delete',
        'file_info' => 'File Information',
        'uploader' => 'Uploader',
        'country' => 'Country',
        'device_type' => 'Device Type',
        'expires_at' => 'Expires At',
        'upload' => 'Upload',
        'drag_and_drop' => 'Drag and drop files here or click to upload',
        'file_preview' => 'File Preview',
    ],
    'ar' => [
        'welcome' => 'مرحباً بك في ScreenMix',
        'upload_files' => 'رفع ملفات',
        'my_files' => 'ملفاتي',
        'profile' => 'الملف الشخصي',
        'logout' => 'تسجيل الخروج',
        'register' => 'تسجيل مستخدم جديد',
        'login' => 'تسجيل الدخول',
        'username' => 'اسم المستخدم',
        'email' => 'البريد الإلكتروني',
        'password' => 'كلمة المرور',
        'submit' => 'إرسال',
        'already_have_account' => 'لديك حساب بالفعل؟',
        'dont_have_account' => 'ليس لديك حساب؟',
        'file_name' => 'اسم الملف',
        'uploaded_at' => 'تم الرفع في',
        'download' => 'تحميل',
        'delete' => 'حذف',
        'file_info' => 'معلومات الملف',
        'uploader' => 'صاحب الملف',
        'country' => 'الدولة',
        'device_type' => 'نوع الجهاز',
        'expires_at' => 'تاريخ انتهاء الصلاحية',
        'upload' => 'رفع',
        'drag_and_drop' => 'اسحب الملفات هنا أو انقر للرفع',
        'file_preview' => 'معاينة الملف',
    ]
];
?>